[global]
exclude = ["**/CHANGELOG.md"]
disable = ["MD041"]
extend-enable = ["MD060"]

[MD013]
line-length = 0
reflow = true
reflow-mode = "sentence-per-line"

[MD024]
siblings_only = true

[MD033]
allowed_elements = ["p", "img"]

[MD060]
style = "aligned"
